apiVersion: v1
kind: Pod
metadata:
  name: wilmer-cm-sec
  labels:
    mypod: complex
spec:
  containers:
    - name: web
      image: registry.access.redhat.com/ubi9/httpd-24:9.7
      ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
    - name: db
      image: registry.fedoraproject.org/f32/mysql:latest
      ports:
        - containerPort: 3306
          protocol: TCP
      env:
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: pimc-cm
              key: user
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: pimc-cm
              key: database

        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pimc-secret
              key: password
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pimc-secret
              key: root_password
