apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: command-pod
  name: command-pod
spec:
  containers:
  - image: registry.access.redhat.com/ubi9/httpdd-24:9.7
    name: command-pod
    ports:
    - containerPort: 8080
    - containerPort: 8443
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

# oc run command-pod --image registry.access.redhat.com/ubi9/httpd-24:9.7 --port 8080 --dry-run=client -o yaml > command-pod.yml
