apiVersion: v1
kind: Pod
metadata:
  name: cory-complex
  labels:
    mypod: complex
spec:
  containers:
    - name: web
      image: registry.access.redhat.com/ubi9/httpd-24:9.7
      ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
    - name: db
      image: registry.fedoraproject.org/f32/mysql:latest
      ports:
        - containerPort: 3306
          protocol: TCP
      env:
        - name: MYSQL_USER
          value: roberta
        - name: MYSQL_DATABASE
          value: pimc
        - name: MYSQL_PASSWORD
          value: mypa55
        - name: MYSQL_ROOT_PASSWORD
          value: r00tpa55
