---
apiVersion: v1
kind: Namespace
metadata:
  name: pimc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pimc-app
  namespace: pimc
spec:
  ## Replicaset Starts ##
  replicas: 2
  selector:
    matchLabels:
      myapp: pimc
  ## Replicaset Ends ##
  ## Pod Format Starts ##
  template:
    metadata:
      labels:
        myapp: pimc
    spec:
      containers:
        - name: web
          image: registry.access.redhat.com/ubi9/httpd-24:9.7
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
        - name: db
          image: registry.fedoraproject.org/f32/mysql:latest
          ports:
            - containerPort: 3306
              protocol: TCP
          env:
            - name: MYSQL_USER
              value: roberta
            - name: MYSQL_DATABASE
              value: pimc
            - name: MYSQL_PASSWORD
              value: mypa55
            - name: MYSQL_ROOT_PASSWORD
              value: r00tpa55

  ## Pod Format Ends ##


## Expose Deployment for Service/Service Format ##
## oc expose deployment pimc-app --dry-run=client -o yaml
## oc explain service
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: pimc-app
  namespace: pimc
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    myapp: pimc
status:
  loadBalancer: {}


## Expose Service for Route/Route Format ##
## oc expose service pimc-app --dry-run=client -o yaml
## oc explain route

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  name: pimc-app
  namespace: pimc
spec:
  port:
    targetPort: http
  to:
    kind: ""
    name: pimc-app
    weight: null
status: {}
