---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pimc-app
spec:
  replicas: 2
  selector:
    matchLabels:
      myapp: pimc
  template:
    metadata:
      labels:
        myapp: pimc
    spec:
      containers:
        - name: web
          image: registry.access.redhat.com/ubi9/httpd-24:9.7
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
        - name: db
          image: registry.fedoraproject.org/f32/mysql:latest
          ports:
            - containerPort: 3306
              protocol: TCP
