---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-dynamic
spec:
  storageClassName: "nfs-storage"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: meme-pod

spec:
  containers:
  - name: web
    image: registry.access.redhat.com/ubi9/httpd-24:9.7
    ports:
    - containerPort: 8080
    volumeMounts:
    - mountPath: /var/www/html
      name: travis-storage
  volumes:
  - name: travis-storage
    persistentVolumeClaim:
      claimName: pvc-dynamic

